Hm 1
vktrbr/mlsd-course-2024 pull request #1
Opened 2024-11-29 02:36 UTC by vktrbr

2024-12-02 14:57 UTC, setday requested changes

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +```mermaid
Кажется, этот блок немного про другое. `Блок-схема решения` = `Блок-схема процесса работы над MVP / baseline`. [Пример из шаблона](https://github.com/IrinaGoloshchapova/ml_system_design_doc_ru/blob/main/product_schema.png)

Думаю, не стоит удалять эту схему, но точно стоит дополнить нужной (напиши туда про сбор данных, презентации решений и тд)

Отдельное уважение за блок-схему в виде кода! (тоже буду теперь использовать `mermaid` =])

2024-12-02 14:57 UTC, setday commented on README.md
> +**Начните управлять задачами проще и умнее с Graphite Time Management!**
Тут должно быть описание проекта (в `README.md`). Не думаю, что рекламные слоганы тут уместны.

2024-12-02 14:57 UTC, setday commented on README.md
> +перегруженных Jira или Google Sheets — мы делаем планирование задач интуитивным и умным.
Слишком абстрактное описание. Я из него не очень понял, что это: если это таск-треккер, то лучше сравнивать с [YouTrack](https://youtrack.jetbrains.com/) или [Yandex Tracker](https://yandex.cloud/ru/services/tracker?utm_referrer=https%3A%2F%2Fwww.google.com%2F), если это просто планировщик задач, то функционал `Напоминания о рисках и пересечениях`, `Расставьте задачи по важности и срокам` точно не делает его проще `Google Sheets`. Как раз описать, что из этого решается и стоит описать тут.

Вообще, в описании лучше не сравнивать свой продукт с другими.

2024-12-02 14:57 UTC, setday commented on README.md
> +pre-commit install
Зачем пользователям устанавливать `pre-commit`-е зависимости? Обычно даже создают два разных  `requirements.txt`: один с общими зависимостями, другой с общими + dev (black, ruff, ...)

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +    - Мобильные и десктопные приложения.
`Что входит в скоуп проекта/итерации, что не входит` должен соответствовать бизнес-требованиям - тут же они отличаются. Либо стоит расширить список БТ (не обязательно добавив все пункты, достаточно добавить область задач в БТ), если данные задачи действительно важны, либо довнести задачи в дальнейшие планы развития (но это стоит сделать только для того, что не входит в скоуп)

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +    1. Удобный интерфейс (список задач, простая навигация).
Общее требование. Почти никогда не существует задач с требование: "интерфейс можете сделать каким угодно - плохим или хорошим". К тому же, выполнение данного критерия очень сложно проверить - только путем сравнения.

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +- **Успешный пилот:** Пользователи сообщают о снижении пропущенных дедлайнов и удобстве
`удобстве использования` - очень абстрактный критерий - как его оценивать? Если тут речь идет о снижении времени первичного знакомства, то так и стоит написать. Возможно, тут речь идет про среднее время на постановку дедлайнов и количество переходов на неправильные страницы.

2024-12-02 14:57 UTC, setday commented on README.md
> +
Ещё стоит написать инструкцию по запуску, если архитектура файлов примерно понятна.

2024-12-02 14:57 UTC, setday commented on README.md
> +- Экономия времени и снижение стресса.
Я не стрессую, когда ставлю дедлайны)

PS: мне кажется, не сильно много кто стрессует от факта выставления дд.

2024-12-02 14:57 UTC, setday commented on pyproject.toml
> +line-length = 88
Тут точно не нужны `exclude`-ы?

```
'''
(
    ^\.git
    | ^\.hg
    | ^\.mypy_cache
    | ^\.tox
    | ^\.venv
    | _build
    | buck-out
    | build
    | dist
)
'''
```
Типа таких.

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +    - Конфиденциальность данных пользователя должна быть гарантирована.
Кажется, тут ещё нужно описать то, что есть в `Требования к системе`.

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +    - Простые уведомления (email).
Что означает `простые`? Какого функционала не будет?

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +    - Простые уведомления (email).
`Интеграция с Google Calendar` на каком уровне? Полная или только частичная?

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +  развития.
Какой смысл от документации, если качество кода может быть любым?)

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +
Кажется, в технический долг стоит добавить минимум "хороший уровень AI предсказаний", ибо в БО написано "Ограниченные данные на старте — модель может быть неточной в начале."

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +    - Конфиденциальность данных пользователя должна быть гарантирована.
+ отсутствуют технические БО

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +      функционала).
Кажется, это не БО, а как раз скоуп

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +  приоритетам и времени в календаре.
А остальные части того, что входит в скоуп.

+ задачи стоит расписывать более подробно.

2024-12-02 14:57 UTC, setday commented on docs/ml_system_design_doc.md
> +  перегрузки и просрочек за счет автоматизации планирования с помощью AI.
Слишком абстрактно: стоит расписать, что за управление задач и с помощь. каких иснструментов

2024-12-02 20:04 UTC, vktrbr commented on README.md
> +pre-commit install
- [x] pre-commit – согласен, пользователю не нужен 
- [x] requirements-dev.txt – согласен лучше добавить

2024-12-02 22:51 UTC, vktrbr commented on docs/ml_system_design_doc.md
> +```mermaid
Добавлю вот такую Блок-схема процесса работы над MVP моделью

<img width="1588" alt="Screenshot 2024-12-02 at 23 50 42" src="https://github.com/user-attachments/assets/73565e26-84aa-4c7c-a876-3b6d396a92cf">

2024-12-02 22:51 UTC, vktrbr commented on README.md
> +**Начните управлять задачами проще и умнее с Graphite Time Management!**
+

2024-12-02 23:04 UTC, vktrbr commented on README.md
> +перегруженных Jira или Google Sheets — мы делаем планирование задач интуитивным и умным.
Написал более предметно 
**Graphite Time Management** — предсказание времени выполнения задач на основе истории их выполнения
и других параметров. Помогает более точно оценить срок выполнения задачи (задача решаемая в рамках
курса). Вне рамок курса будет реализовано управление задачами, приоритетами и сроками.

2024-12-03 01:07 UTC, vktrbr reviewed
Спасибо за подробную обатную связь. Эта связь направила меня на более грамотную спецификацию скоупа работ и целей на этот курс и проект.

2024-12-05 11:47 UTC, PikaChuChuMF reviewed
В целом все хорошо, если закрыть тудушки - вообще прекрасно будет..
Понравилось внимание практической части, реализация блок-схемы)

2024-12-05 11:47 UTC, PikaChuChuMF commented on README.md
Хороший readme, молодец что уделил достаточно внимание установке, если есть какие-то графические материалы - их тоже можно добавить, примеры и юзкейсы - в ритме такое полезно, это лицо проекта для конечного пользователя)

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +      предсказаний сроков выполнения задач лучше, чем ручное.
В критериях успеха для точности предсказания было бы неплохо добавить какие-то метрики из базовых, метрики для классической задачи регрессии как мне кажется тут вполне могут подойти

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +2. Производительность. Время отклика модели не должно превышать 10 секунд на один запрос.
Можно добавить немного обоснований этому требованию - почему именно 10 секунд, а, например, не 20? Короткого комментария будет достаточно.

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +3. Безопасность. Защита данных пользователей и конфиденциальность информации.
Если есть информация для конкретных критериев безопасности и конфиденциальности - лишним тоже не будет)

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +  зависимости между задачами, аргументировать свои решения.
Иногда хорошей идеей является добавления информация по статьям, примерам решения смежных задач, применения ЛЛМ для решения регрессионный задач в целом

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +### 2.2 Блок-схема решения
Постановку задачи или блок-схему решения можно добавить текстовое описание архитектуры и общих идей решения задачи

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +- Meeting notes, где упоминается задача и что необходимо сделать.
Прекрасный блок - кратко и по делу, молодец)

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +
Можно добавить комментарии - почему именно такой бейзлайн? Т.к сейчас все чаще в качестве базы вижу w2v в подобных задачах. Но можно оставить и так)

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +
Кратко, по делу, лайк)

2024-12-05 11:47 UTC, PikaChuChuMF commented on docs/ml_system_design_doc.md
> +    - Отсутствие критических ошибок в работе модели и API.
Неплохой блок, его можно будет дополнить в процессе конкретизации и разработки)

2024-12-05 14:06 UTC, setday approved these changes
Мне очень нравится, как получилось!

Если действительно поправить TODO и поработать с комментариями второго ревьювера, то получится прекрасный дд 🔥

2024-12-05 20:28 UTC, vktrbr commented on docs/ml_system_design_doc.md
> +      предсказаний сроков выполнения задач лучше, чем ручное.
Добавил метрику взвешенную.

Классические метрики кмк не подходят, тк недооценка ведет к переработкам, а потом к выгоранию и увольнению. Лучше поспорить на встрече за переоценненые сроки и прийти раньше к счастливому заказчику, тем получать пинг за недооценку.

2024-12-05 20:33 UTC, vktrbr commented on docs/ml_system_design_doc.md
> +2. Производительность. Время отклика модели не должно превышать 10 секунд на один запрос.
Добавил примерную прикидку. 
Почему 10? Мы хотим использовать модель во время планирования задач. Условно 10-15 задач берется на одного человека и для каждой нужно предсказать время выполнения. На планировании выделено на одного человека 30 минут. 10 секунд на задачу – это (15 * 10 / 30) / 30 ~ 8.5% = 10% времени на планирование. Больше 10% времени на ожидание ответа от модели выглядит неудобно.

2024-12-05 20:34 UTC, vktrbr commented on docs/ml_system_design_doc.md
> +3. Безопасность. Защита данных пользователей и конфиденциальность информации.
Спасибо за комментарий, дополню ближе к решению вопроса с конфиденциальностью

2024-12-05 20:35 UTC, vktrbr commented on docs/ml_system_design_doc.md
> +
Это самое быстрое и простое кмк. (я забыл про w2v и насколько это просто) – Возможно после tf-idf сразу пойдет w2v, или комбинация w2v + tf-idf 

спасибо за идею!

2024-12-05 20:39 UTC, vktrbr reviewed
Спасибо ревьюеру за ОС. Добавил описание конкретной метрики и значение метрики в текущем процессе, где мы садимся раз в спринт и планируем задачи, используя разные методики.

2024-12-07 11:56 UTC, AnyashaTk approved these changes
Стоит добавить оглавление с сылками на каждый подблок для всех файлов .md

Довольно хорошо все прописано, молодец)
По баллам насколько я вижу будет максимум)

2024-12-07 11:56 UTC, AnyashaTk commented on requirements.txt
> +scikit-learn
Если используешь poetry то имеет смысл генерировать автоматически poetry.lock файл и в нем и toml файле хранить все зависимости, dev тоже можно добавить отдельно если вводить poetry add -D <lib>

Круто что dev и обычные библиотеки разделены уже здесь и сейчас тоже)

2024-12-07 11:56 UTC, AnyashaTk commented on docs/ml_system_design_doc.md
> +    - **Точность предсказаний:** 1.2 (1) – Weighted Accuracy > 50% (Определение ниже)
Можно добавить ссылку чтобы было удобно переходить на определение 
`[Определение ниже](#Метрики)`
И блок с определениями можно вставить где-то в начале для удобства

2024-12-07 14:15 UTC, vktrbr commented on requirements.txt
> +scikit-learn
спасибо!
Не хотел в этом проекте использовать poetry

2024-12-07 14:30 UTC, vktrbr commented on docs/ml_system_design_doc.md
> +    - **Точность предсказаний:** 1.2 (1) – Weighted Accuracy > 50% (Определение ниже)
Добавил

2024-12-07 14:30 UTC, vktrbr commented
@AnyashaTk я могу мерджить?

2024-12-11 22:26 UTC, merged